# Generated by Django 5.2.16 on 2026-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('frameworks', models.JSONField(blank=True, default=list)),
                ('databases', models.JSONField(blank=True, default=list)),
                ('cloud_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='web.profile')),
            ],
        ),
    ]
