# Generated by Django 6.0.6 on 2026-07-13 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_profile_id_gmailconnection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATSResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("job_description", models.TextField()),
                ("resume_json", models.JSONField()),
                ("jd_json", models.JSONField()),
                ("ats_score", models.FloatField(default=0)),
                ("matched_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("recommended_skills", models.JSONField(default=list)),
                ("strengths", models.JSONField(default=list)),
                ("improvements", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technical_skills", models.JSONField(blank=True, default=list)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("frameworks", models.JSONField(blank=True, default=list)),
                ("databases", models.JSONField(blank=True, default=list)),
                ("cloud_skills", models.JSONField(blank=True, default=list)),
                ("soft_skills", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="web.profile",
                    ),
                ),
            ],
        ),
    ]
