# Generated by Django 6.0.7 on 2026-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterjob',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='recruiterjob',
            name='experience_required',
            field=models.CharField(blank=True, help_text='e.g. 2-4 Years or Entry Level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiterjob',
            name='salary',
            field=models.CharField(blank=True, help_text='e.g. ₹6,000,000 - ₹12,000,000 PA or $80k - $100k', max_length=100, null=True),
        ),
    ]
