# Generated by Django 6.0.7 on 2026-07-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_application_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shortlisted", "Shortlisted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
